### PR TITLE
Adds slim language support

### PR DESCRIPTION
**Pull request by filipelinhares**

### CODE REVIEW

**Comment by simurai** [comment]
Thanks for your PR. Is it for https://atom.io/packages/language-slim or maybe https://atom.io/packages/slim-language?

I'm still unsure how many/which languages should be included.. see https://github.com/simurai/duotone-syntax/issues/2. But as said in the comment, we can think about it later again.

**Comment by filipelinhares** [comment]
This is for [slim-language](https://atom.io/packages/slim-language). I found one issue in each package:

The slim-language don't  highlight attrs (the printscreen is after my modification) and don't highlight inline ruby:
image

and language-slim don't highlight attrs:
image

My PR cover the attrs for [slim-language](https://atom.io/packages/slim-language) package

**Comment by simurai** [comment]
Is it possible to fix it in both language packages without messing each other up?

Or maybe it's better to fix it in the actual language package itself and not each theme.

**Comment by filipelinhares** [comment]
To remove the `slim.less` file we can replace [`.html.attribute-name`](https://github.com/simurai/duotone-dark-syntax/blob/master/styles/languages/_base.less#L43) with just `.attribute-name`.

I don't know exactly how language package works, but the problem is the parser isn't adding the right classes.
Maybe [this line](https://github.com/IanMitchell/slim-language/blob/master/grammars/slim.cson#L250-L252) could be the point to solve the [language-slim](https://atom.io/packages/language-slim) problem with attributes.

**Comment by simurai** [comment]
> To remove the `slim.less` file we can replace `.html.attribute-name` with just `.attribute-name`.

That might be a good idea. Actually, in `_base.less`, there shouldn't be any language specific selectors anyways.

> Maybe this line could be the point to solve the language-slim problem with attributes.

Ya, currently "language-slim" adds `entity name tag slim` to attributes. A more specific `attribute-name` would help. Feel free to open an issue there.

**Pull request merged**
