### PR TITLE
Color schemes

### PR DESCRIPTION
**Pull request by simurai**
This PR adds 4 extra color schemes:

duo

### CODE REVIEW

**Comment by simurai** [comment]
@braver do you like it?

Code is a modified version of @Alchiadus's https://github.com/Alchiadus/base16-syntax because "I have no idea what I'm doing".. but somehow seems to work.

Currently it just changes the 2 hues, but it might be better to also modify saturation/lightness because some colors seem darker/lighter.

**Comment by Alchiadus** [comment]
> Code is a modified version of @Alchiadus's https://github.com/Alchiadus/base16-syntax because "I have no idea what I'm doing".. but somehow seems to work.

@simurai @braver If you have any questions, I'd be happy to explain.

There is one issue with the current implementation: after upgrading the theme the default values are loaded, instead of the user specified settings. This only happens directly after an upgrade of the theme and reloading or restarting Atom correctly honors the user settings. I created an issue for this just now on [base16-syntax](https://github.com/Alchiadus/base16-syntax) if you'd like to track this: https://github.com/Alchiadus/base16-syntax/issues/16, along with my current understanding of the problem.

There's also a minor performance improvement to be gained: currently the user settings are written to disk and the syntax theme's stylesheets are reloaded upon activation of the theme, even if they did not change.
The latter is easy to fix: I did this in hopes of preventing the issue mentioned above, but this seems to have no effect during an upgrade and I don't expect a user to manually edit `styles/syntax-variables.less`, so that code could simply be removed.
The former is a bit harder. It would require at least a read (and parsing) of `styles/syntax-variables.less` to read the variables and see if a write is necessary and I am not sure if this optimization is worth it.

I don't think there exists an `afterUpgrade` where we could restore user settings? This could potentially solve both the default issue and the performance improvement, as writing the user settings and reloading the stylesheets during activation would never be necessary.

**Comment by braver** [comment]
Writing stuff to disk just seems like a hack to me. We had a similar discussion as a possible solution for user configurable themes and in the end just didn't want to go there. If we're going to make fixed variants instead of "pick any color you like", wouldn't it make more sense to add a little grunt build step to this package? That would keep complexity of the theme code way down. To me, `lib/duotone.coffee` just feels way too complex and fragile for what we're trying to accomplish. Why solve this in user-config-space and not in design-space?

**Comment by Alchiadus** [comment]
I completely agree this is a hack and I would like to move away from this method as soon as possible. The problem is that every package expects a `styles/syntax-variables.less` file and we cannot point Atom to the location of this file; its location is hardcoded. Before, I did not write to disk and instead did it in-memory by providing the variables as a `preliminaryContent` string to be concatenated with the contents of a file read from disk and passed to the less compiler. This is what the `applyStylesheet` method does and is essentially how Atom applies the default variables as fallback when a `styles/syntax-variables.less` file does not exist. This works fine for the syntax theme's stylesheets, but this approach breaks any package that imports `styles/syntax-variables.less` since that file either does not exist (and thus the fallbacks are used) or is not updated with the correct variables set by the user after the syntax theme is loaded (and thus the theme's defaults are used by other packages). I took a long time to fix this problem because I wanted to find a different approach than simply writing to disk but I don't think it can be avoided right now if you want to offer users customization.

**Comment by simurai** [comment]
@Alchiadus Thanks. Good to know about those issues. Another thing that might be tricky: Once you picked the scheme names, you can't really change them. Because people's config still try to load a non-existing scheme and throw some errors?

---

> @braver If we're going to make fixed variants instead of "pick any color you like"

Picking the 2 hues was my first plan, but then I thought it probably is better to have curated combos. Or even tweak some more like brightness/saturation. Basically different versions of `color.less`.

> @braver wouldn't it make more sense to add a little grunt build step to this package?

Would that generate different themes or the schemes switched with an attribute like `[theme-duotone-dark-syntax-scheme="navy-gold"]`?

**Comment by Alchiadus** [comment]
> @simurai Thanks. Good to know about those issues. Another thing that might be tricky: Once you picked the scheme names, you can't really change them. Because people's config still try to load a non-existing scheme and throw some errors?

I think this scenario can be gracefully handled. I'd probably do something along these lines:
1. Try to apply the scheme in the settings and catch any errors.
2. In the catch block, check if the scheme in the settings matches any renamed scheme.
2.a. If it does, apply the renamed scheme instead and update the user's scheme field in the settings with the new name.
2.b. If it doesn't, apply the default scheme (although this should never happen unless the user manually modified the setting to a non-existing scheme name).
3. Mention the rename mapping in the `CHANGELOG.md` so users don't get confused when they notice their choice of scheme in the settings has been changed.

**Comment by braver** [comment]
Right, so as I understand it now, Atom doesn't support dynamic themes and packages need a reliable syntax-variables.less file. There would be two ways to accomplish this:
1. the proposed write-a-file-to-disk method
2. create separate themes for each color combo, possibly building the variations on a script

Although configurable themes are awesome, what you're proposing here feels to me too far outside of what Atom supports. I would prefer to solve the problem in design-space and publish separate color schemes. For one because I don't feel like supporting and explaining quirks like those in the proposed solution. Point in case, I get about three issues a week for stuff in terminal-package or Zen that just doesn't really work as expected in some situations and just explaining and closing those is more effort than is worth it. Also, the code proposed here is not something I can help maintain and I want these themes to be around and portable to Atom 2.0 or whatever without too many headaches.

Now if you guys are totally into this, there is no reason to let me slow you down. But it's beyond what I'm comfortable with for anything that needs longevity.

**Comment by simurai** [comment]
> @braver the code proposed here is not something I can help maintain

Yeah, I guess I shouldn't just copy & paste code if I don't really understand it. :innocent:

Ok, I'll close this again and maybe create other themes that are variations of this one.

@Alchiadus Maybe in your case where there is like 20-30 schemes it still makes sense with saving to disk.

Ok, thanks for checking it out. :bow:

**Comment by braver** [comment]
👍🏻

**Pull request closed without merging**
