### PR TITLE
Added tmTheme file

### PR DESCRIPTION
**Pull request by vb**
I started cloning this theme to Sublime Text (and Textmate etc) with the help of http://tmtheme-editor.herokuapp.com/
It probably needs more syntax testing to have the same language compatibility as the original version.

### CODE REVIEW

**Comment by varemenos** [comment]
Shouldn't this been in a different repo?

**Comment by simurai** [comment]
Thanks for adding a TM port, but I think I'm gonna keep this repo "Atom only". Just because the structure is quite different and probably not that easy to maintain manually.

If you want to keep your port as a fork, that's totally fine. You might also be interested in  https://github.com/davidosomething/duotone-base16 which can be used to generate different ports from DuoTone themes. I think the color mapping could need some improvements.

**Comment by simurai** [comment]
Tweaked it a bit here: https://gist.github.com/simurai/de2dbbbd7eabf25bec18

The colors look fine in the http://tmtheme-editor.herokuapp.com/ theme editor, but then when testing it in TextMate and Sublime, for some reason the syntax highlighting is off:

screen shot 2016-01-11 at 11 56 20 am

screen shot 2016-01-11 at 11 54 55 am

screen shot 2016-01-11 at 11 55 12 am

**Comment by atelierbram** [comment]
What helps are "hints" about the syntax-highlighting groups where the specific tags belong to. With activating the command `displayName`, and hitting the function keys `<Ctrl><Shift><P>` this can be done. 

It took some effort to figure out a reliable workflow, btw I [write about it here](http://atelierbram.github.io/blog/colorschemes-sublime/), and was able to do some work today on the base16 template for Sublime, and [it's getting there](https://github.com/atelierbram/syntax-highlighting/tree/master/duotones/output/textmate).

screenshot javaScript file in DuoTone Dark syntax-highlighting file

Thinking about setting up a separate repo for Duotone-Sublime for easy cloning into Packages folder + convenient updating.

**Comment by simurai** [comment]
Ok, I'm gonna close this for now as `wontfix`. I'm probably still gonna juggle a bit more with the Atom version and it keeps it easier to maintain.

@viktorbergehall But thanks for the PR and you're more than welcome to keep the TM port.

**Pull request closed without merging**
